### ISSUE TITLE
help with my broken vit?

### ISSUE THREAD

**Issue by ahillio** [vit-project/vit#234]
I accidentally deleted some critical files (not even sure which ones, user config files, maybe ~/.local) and now when I try re-installing vit won't finish loading...

```
$ vit
^CTraceback (most recent call last):
  File "/usr/local/bin/vit", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/usr/local/lib/python3.7/dist-packages/vit/application.py", line 70, in __init__
    self.load_early_config()
  File "/usr/local/lib/python3.7/dist-packages/vit/application.py", line 78, in load_early_config
    self.task_config = TaskParser(self.config)
  File "/usr/local/lib/python3.7/dist-packages/vit/config_parser.py", line 197, in __init__
    self.get_task_config()
  File "/usr/local/lib/python3.7/dist-packages/vit/config_parser.py", line 205, in get_task_config
    returncode, stdout, stderr = self.command.run('task _show', capture_output=True)
  File "/usr/local/lib/python3.7/dist-packages/vit/process.py", line 31, in run
    stdout, stderr = proc.communicate()
  File "/usr/lib/python3.7/subprocess.py", line 964, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1715, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

I can do `vit --version`, `vit --help` which both work, but `vit` never fully loads the program.

I have no idea how to debug or troubleshoot this.

I tried `pip3 uninstall vit` and reinstalling but the issue affects the new re-installed version.  I then tried installing via sudo and the issue is the same.

Can anyone suggest what I might investigate or try to get a working vit?  Thanks <3

**Comment by thehunmonkgroup** [comment]
Pretty sure you broke TaskWarrior, not VIT.

VIT is not able to execute the following TaskWarrior command:

```
returncode, stdout, stderr = self.command.run('task _show', capture_output=True)
```

**Comment by ahillio** [comment]
Awesome, thanks for that quick nudge!  Taskwarrior was missing software that one of its hook scripts relied on, not related to vit itself.  Now I'm back in action :)

**Comment by nickgrim** [comment]
@ahillio: close this ticket if you're done?

**Comment by ahillio** [comment]
oh there's a "close" button! thanks :)
