### ISSUE TITLE
vit not run

### ISSUE THREAD

**Issue by Monirzadeh** [vit-project/vit#239]
I install vit  from ubuntu 20.04 repository and set `XDG_Base_Directory` [for task](https://wiki.archlinux.org/index.php/XDG_Base_Directory)

when I try to run vit  after generate `path/to/home/directory/.vit/config.ini`get this error
```
Traceback (most recent call last):
  File "/usr/bin/vit", line 11, in <module>
    load_entry_point('vit==2.0.0', 'console_scripts', 'vit')()
  File "/usr/lib/python3/dist-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/usr/lib/python3/dist-packages/vit/application.py", line 73, in __init__
    self.refresh(False)
  File "/usr/lib/python3/dist-packages/vit/application.py", line 832, in refresh
    self.build_main_widget()
  File "/usr/lib/python3/dist-packages/vit/application.py", line 866, in build_main_widget
    self.init_task_list()
  File "/usr/lib/python3/dist-packages/vit/application.py", line 501, in init_task_list
    self.model = TaskListModel(self.task_config, self.reports)
  File "/usr/lib/python3/dist-packages/vit/task.py", line 15, in __init__
    self.tw = tasklib.TaskWarrior(self.data_location)
  File "/usr/lib/python3/dist-packages/tasklib/backends.py", line 130, in __init__
    os.makedirs(data_location)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/task'
```

**Comment by scottkosty** [comment]
@Monirzadeh did you fix the problem?

**Comment by Monirzadeh** [comment]
Yes
Problem is in wrong path for data in my config.
Sorry for open an issue

**Comment by scottkosty** [comment]
I see, glad you got it figured out.
