### ISSUE TITLE
vit crashing on report

### ISSUE THREAD

**Issue by supersambo** [vit-project/vit#250]
vit crashes at startup when using personalized report. 

Error:
```
Traceback (most recent call last):
  File "/usr/bin/vit", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/usr/lib/python3.8/site-packages/vit/application.py", line 73, in __init__
    self.refresh(False)
  File "/usr/lib/python3.8/site-packages/vit/application.py", line 832, in refresh
    self.build_main_widget()
  File "/usr/lib/python3.8/site-packages/vit/application.py", line 876, in build_main_widget
    self.update_report(self.report)
  File "/usr/lib/python3.8/site-packages/vit/application.py", line 851, in update_report
    self.update_task_table()
  File "/usr/lib/python3.8/site-packages/vit/application.py", line 498, in update_task_table
    self.table.update_data(self.reports[self.report], self.model.tasks)
  File "/usr/lib/python3.8/site-packages/vit/task_list.py", line 85, in update_data
    self.set_column_metadata()
  File "/usr/lib/python3.8/site-packages/vit/task_list.py", line 224, in set_column_metadata
    self.add_column(name, self.report['labels'][idx], formatter_class(name, self.report, self.formatter, **kwargs))
KeyError: 'labels'
```

Report work defined in `.taskrc` is set as default in `.vit/config.ini`

```
# Reports
report.work.description = work
report.work.columns = id,project,description,tags,due,priority,scheduled,start
report.work.sort = start-,scheduled+,project+,project+,urgency
report.work.filter = status:pending 
```

python: 3.8
vit: 2.0.0 (installed via pip)

**Comment by thehunmonkgroup** [comment]
Fixed in https://github.com/scottkosty/vit/commit/e43dca5ef4c874220dd51fde2502ce98d2692022

You can work around the bug in the current release by providing an explicit ```labels``` attribute in your report configuration:

```dosini
report.work.labels = id,project,description,tags,due,priority,scheduled,start
```
