### ISSUE TITLE
Error after installing vit 

### ISSUE THREAD

**Issue by sucrecacao** [vit-project/vit#284]
**Describe the bug**
Error after installing vit 

**To Reproduce**

Installing vit through the INSTALL.md instruction, with python3.7
Then I try to run `vit` and I got:
```
Traceback (most recent call last):
  File "/home/joe/.local/bin/vit", line 8, in <module>
    sys.exit(main())
  File "/home/joe/.local/lib/python3.7/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/home/joe/.local/lib/python3.7/site-packages/vit/application.py", line 70, in __init__
    self.load_early_config()
  File "/home/joe/.local/lib/python3.7/site-packages/vit/application.py", line 79, in load_early_config
    self.reports = self.task_config.get_reports()
  File "/home/joe/.local/lib/python3.7/site-packages/vit/config_parser.py", line 336, in get_reports
    self.reports[report_name] = self.rectify_report(report_name, report)
  File "/home/joe/.local/lib/python3.7/site-packages/vit/config_parser.py", line 340, in rectify_report
    report['subproject_indentable'] = self.has_project_column(report_name) and self.has_primary_project_ascending_sort(report)
  File "/home/joe/.local/lib/python3.7/site-packages/vit/config_parser.py", line 344, in has_project_column
    return self.get_column_index(report_name, 'project') is not None
  File "/home/joe/.local/lib/python3.7/site-packages/vit/config_parser.py", line 351, in get_column_index
    return self.reports[report_name]['columns'].index(column) if column in self.reports[report_name]['columns'] else None
KeyError: 'columns'
```

**Comment by thehunmonkgroup** [comment]
please install the latest beta, that bug has already been fixed: https://pypi.org/project/vit/2.1.0b1/
