### ISSUE TITLE
vit fails to launch after installation

### ISSUE THREAD

**Issue by marekkowalczyk** [vit-project/vit#285]
**Describe the bug**

````
$ vit

/usr/local/Cellar/vit/2.0.0_2/libexec/lib/python3.9/site-packages/tzlocal/unix.py:141: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while start is not 0:
/Users/marekkowalczyk/.vit/config.ini doesn't exist, create? (y/n): y

/Users/marekkowalczyk/.vit/config.ini created. This is the default user configuration file.

It is heavily commented with explanations and lists the default values for all available user configuration variables. Check it out!

Press enter to continue...
Traceback (most recent call last):
  File "/usr/local/bin/vit", line 33, in <module>
    sys.exit(load_entry_point('vit==2.0.0', 'console_scripts', 'vit')())
  File "/usr/local/Cellar/vit/2.0.0_2/libexec/lib/python3.9/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/usr/local/Cellar/vit/2.0.0_2/libexec/lib/python3.9/site-packages/vit/application.py", line 70, in __init__
    self.load_early_config()
  File "/usr/local/Cellar/vit/2.0.0_2/libexec/lib/python3.9/site-packages/vit/application.py", line 78, in load_early_config
    self.task_config = TaskParser(self.config)
  File "/usr/local/Cellar/vit/2.0.0_2/libexec/lib/python3.9/site-packages/vit/config_parser.py", line 197, in __init__
    self.get_task_config()
  File "/usr/local/Cellar/vit/2.0.0_2/libexec/lib/python3.9/site-packages/vit/config_parser.py", line 209, in get_task_config
    hierarchy, values = line.split('=')
ValueError: too many values to unpack (expected 2)

````

**To Reproduce**

````
$ brew install vit

==> Downloading https://homebrew.bintray.com/bottles/vit-2.0.0_2.mojave.bottle.2.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/e1187a8c5a4b75d55bcda3758f1a70375f7cb8fd995239383de172dc408cf23e?resp
######################################################################## 100.0%
==> Pouring vit-2.0.0_2.mojave.bottle.2.tar.gz
🍺  /usr/local/Cellar/vit/2.0.0_2: 1,452 files, 9.3MB

$ vit
````

**Expected behavior**

````vit```` launches.

**Test case**
If reproducing your issue requires any TaskWarrior setup, please produce a [test case](https://github.com/vit-project/vit/blob/2.x/TEST-CASE.md) script.

**Comment by thehunmonkgroup** [comment]
This is most likely an issue with your ```.taskrc``` configuration.

Try starting with a default/minimal ```.taskrc```. From there you can work towards finding the problem line.

**Comment by cgoetzke** [comment]
**Note for posterity: This post is actually an unrelated issue. My mistake. Just skip over this post.**

I have what looks like a very similar problem. Apologies if I'm wrong.

I just installed `vit`, and it won't start:
```
 clg  ~  vit
Traceback (most recent call last):
  File "/usr/bin/vit", line 11, in <module>
    load_entry_point('vit==2.0.0', 'console_scripts', 'vit')()
  File "/usr/lib/python3.8/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/usr/lib/python3.8/site-packages/vit/application.py", line 70, in __init__
    self.load_early_config()
  File "/usr/lib/python3.8/site-packages/vit/application.py", line 79, in load_early_config
    self.reports = self.task_config.get_reports()
  File "/usr/lib/python3.8/site-packages/vit/config_parser.py", line 336, in get_reports
    self.reports[report_name] = self.rectify_report(report_name, report)
  File "/usr/lib/python3.8/site-packages/vit/config_parser.py", line 340, in rectify_report
    report['subproject_indentable'] = self.has_project_column(report_name) and self.has_primary_project_ascending_sort(report)
  File "/usr/lib/python3.8/site-packages/vit/config_parser.py", line 344, in has_project_column
    return self.get_column_index(report_name, 'project') is not None
  File "/usr/lib/python3.8/site-packages/vit/config_parser.py", line 351, in get_column_index
    return self.reports[report_name]['columns'].index(column) if column in self.reports[report_name]['columns'] else None
KeyError: 'columns'
 clg  ~  
```

I only recently installed Taskwarrior. I've added some tasks & it seems to work fine. My .taskrc is the default auto-generated one with no modifications:
```
# [Created by task 2.5.3 2/26/2021 21:29:31]
# Taskwarrior program configuration file.
# For more documentation, see http://taskwarrior.org or try 'man task', 'man task-color',
# 'man task-sync' or 'man taskrc'

# Here is an example of entries that use the default, override and blank values
#   variable=foo   -- By specifying a value, this overrides the default
#   variable=      -- By specifying no value, this means no default
#   #variable=foo  -- By commenting out the line, or deleting it, this uses the default

# Use the command 'task show' to see all defaults and overrides

# Files
data.location=~/.task

# Color theme (uncomment one to use)
#include /usr//usr/share/doc/packages/task/rc/light-16.theme
#include /usr//usr/share/doc/packages/task/rc/light-256.theme
#include /usr//usr/share/doc/packages/task/rc/dark-16.theme
#include /usr//usr/share/doc/packages/task/rc/dark-256.theme
#include /usr//usr/share/doc/packages/task/rc/dark-red-256.theme
#include /usr//usr/share/doc/packages/task/rc/dark-green-256.theme
#include /usr//usr/share/doc/packages/task/rc/dark-blue-256.theme
#include /usr//usr/share/doc/packages/task/rc/dark-violets-256.theme
#include /usr//usr/share/doc/packages/task/rc/dark-yellow-green.theme
#include /usr//usr/share/doc/packages/task/rc/dark-gray-256.theme
#include /usr//usr/share/doc/packages/task/rc/dark-gray-blue-256.theme
#include /usr//usr/share/doc/packages/task/rc/solarized-dark-256.theme
#include /usr//usr/share/doc/packages/task/rc/solarized-light-256.theme
#include /usr//usr/share/doc/packages/task/rc/no-color.theme

```
If it's interesting, I installed `vit` as an OpenSUSE Tumbleweed package:
```
 clg  ~  zypper info vit
Loading repository data...
Reading installed packages...


Information for package vit:
----------------------------
Repository     : openSUSE-Tumbleweed-Oss (20210219)
Name           : vit
Version        : 2.0.0-1.2
Arch           : noarch
Vendor         : openSUSE
Installed Size : 639.2 KiB
Installed      : Yes
Status         : up-to-date
Source package : vit-2.0.0-1.2.src
Summary        : Visual Interactive Taskwarrior full-screen terminal interface
Description    : 
    Visual Interactive Taskwarrior full-screen terminal interface.
    Features:
     * Fully-customizable key bindings (default Vim-like)
     * Uncluttered display
     * No mouse
     * Speed
     * Per-column colorization
     * Advanced tab completion
     * Multiple/customizable themes
     * Override/customize column formatters
     * Intelligent sub-project indenting

 clg  ~  
```

Is my problem related, or is this completely irrelevant to this issue?

**Comment by thehunmonkgroup** [comment]
@cgoetzke different issue. Next 2.x release will include the fix for the issue you're seeing, but for now, install the latest beta release or the 2.x dev branch.

**Comment by cgoetzke** [comment]
Sorry for the issue hijack, and thanks for the pointer!

Update: 2.1.0 release works for me. Thanks again!
