### ISSUE TITLE
Vit can't print a report which uses "depends" as sort option

### ISSUE THREAD

**Issue by mhalano** [vit-project/vit#300]
**Describe the bug**

I'm trying to do a sort in a report using "depends" and "project" columns. The idea is to put all blocked tasks at the end of the report.

**To Reproduce**

Change the sort of any report to something like this:
`report.someday.sort=depends+,project+`
The execution of `task someday` should work as expected (the blocked tasks in the end) but `vit someday` will crash with this message:
```
Traceback (most recent call last):
  File "/usr/bin/vit", line 33, in <module>
    sys.exit(load_entry_point('vit==2.0.0', 'console_scripts', 'vit')())
  File "/usr/lib/python3/dist-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/usr/lib/python3/dist-packages/vit/application.py", line 73, in __init__
    self.refresh(False)
  File "/usr/lib/python3/dist-packages/vit/application.py", line 834, in refresh
    self.build_main_widget()
  File "/usr/lib/python3/dist-packages/vit/application.py", line 878, in build_main_widget
    self.update_report(self.report)
  File "/usr/lib/python3/dist-packages/vit/application.py", line 853, in update_report
    self.update_task_table()
  File "/usr/lib/python3/dist-packages/vit/application.py", line 500, in update_task_table
    self.table.update_data(self.reports[self.report], self.model.tasks)
  File "/usr/lib/python3/dist-packages/vit/task_list.py", line 84, in update_data
    self.sort()
  File "/usr/lib/python3/dist-packages/vit/task_list.py", line 188, in sort
    self.tasks = sorted(self.tasks, key=cmp_to_key(comparator))
  File "/usr/lib/python3/dist-packages/vit/task_list.py", line 178, in comparator
    return -1 if first[column] < second[column] else 1 if first[column] > second[column] else 0
TypeError: '<' not supported between instances of 'LazyUUIDTaskSet' and 'set'
```

**Expected behavior**

The report should open normally and the blocked tasks should be printed in the end.

**Test case**
If reproducing your issue requires any TaskWarrior setup, please produce a [test case](https://github.com/vit-project/vit/blob/2.x/TEST-CASE.md) script.
I'm using Ubuntu 21.04 with the native package available, version 2.0.0

**Comment by mhalano** [comment]
Installed the version 2.1.0 using `pip install` and seems to have the same behavior.

**Comment by thehunmonkgroup** [comment]
I believe this should be fixed in `tasklib`, which is a library we depend on, and have filed https://github.com/robgolding/tasklib/issues/96 to move that forward.

**Comment by thehunmonkgroup** [comment]
Looks like https://github.com/GothenburgBitFactory/tasklib/pull/107 addresses the underlying problem in `tasklib`, just waiting on a new release and we can re-test with the fixed library.

**Comment by RonMcKay** [comment]
@mhalano tasklib got a new release on November 17, 2022. Did that solve your issue?

**Comment by mhalano** [comment]
Hi @RonMcKay, I don't use taskwarrior/vit/etc anymore, but I did a quick test (add some tasks to fill the report) and it seems is ok now. Thanks for your help.
