### ISSUE TITLE
vit fails after upgrading to task 2.6.0

### ISSUE THREAD

**Issue by linuxcaffe** [vit-project/vit#304]
**Describe the bug**
Today, after upgrading to the latest task, in attempting to run vit, the background opens with 
Welcome to VIT
Loading...
.. and then hangs :-( 

**To Reproduce**
upgrade to latest task, run vit

**Expected behavior**
vit runs nicely, like before 

**Test case**
If reproducing your issue requires any TaskWarrior setup, please produce a [test case](https://github.com/vit-project/vit/blob/2.x/TEST-CASE.md) script.
```
➜  ~ vit
Traceback (most recent call last):
  File "/usr/local/bin/vit", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/usr/local/lib/python3.6/dist-packages/vit/application.py", line 75, in __init__
    self.loop.run()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 814, in _loop
    ready, w, err = select.select(fds, [], fds)
KeyboardInterrupt
```

**Comment by tbabej** [comment]
@linuxcaffe Can you check you have upgraded `tasklib` to the [latest 2.4.0 release](https://github.com/GothenburgBitFactory/tasklib/releases/tag/2.4.0)? The older versions of tasklib do not work with 2.6.0.

**Comment by scottkosty** [comment]
@linuxcaffe I don't have much time these days to put into vit/taskwarrior, but I just wanted to say it's nice to see you around DJP :)

**Comment by linuxcaffe** [comment]
pip3 install -U tasklib did the job! Thanks again @tbabej ! Hello there @scottkosty ! Yes, it HAS been a while! Houpe you're doing well, maybe seeya in the discord channel!

**Comment by thehunmonkgroup** [comment]
I bumped the min tasklib version for vit in https://github.com/vit-project/vit/commit/9e07241f644be0412245cc1a7a6faaa39f57a45a
