### ISSUE TITLE
AttrSpecError: Unrecognised color specification in background ('black,bold') when starting vit with custom themes

### ISSUE THREAD

**Issue by onlyphantom** [vit-project/vit#322]
## The Bug

It seems like there is a conflict with how vit handles acceptable color specification vs some taskwarrior themes. This has happened in the past with another theme and I wasn't able to reproduce it. This week it came up again with another theme, and this time I decided to do a little bit of poking. 

To reproduce, consider a theme like [the nord theme](https://github.com/arcticicestudio/igloo/blob/c6534e6392960bb335d0258e13e3b2a48424c372/snowblocks/taskwarrior/nord.theme). Clone it, then modify the `~/.taskrc` file to include it:

```
include ~/vaults/tw-nord.theme
```

Everything else stays the same (no other modifications to `vit` or `taskrc`).  When you try to start `vit` now, this comes up:

```
Traceback (most recent call last):
  File "/home/samuel/.local/bin/vit", line 8, in <module>
    sys.exit(main())
  File "/home/samuel/.local/lib/python3.8/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/home/samuel/.local/lib/python3.8/site-packages/vit/application.py", line 74, in __init__
    self.refresh(False)
  File "/home/samuel/.local/lib/python3.8/site-packages/vit/application.py", line 898, in refresh
    self.loop.screen.register_palette(self.theme)
  File "/home/samuel/.local/lib/python3.8/site-packages/urwid/display_common.py", line 856, in register_palette
    self.register_palette_entry(*item)
  File "/home/samuel/.local/lib/python3.8/site-packages/urwid/display_common.py", line 938, in register_palette_entry
    high_256 = AttrSpec(foreground_high, background_high, 256)
  File "/home/samuel/.local/lib/python3.8/site-packages/urwid/display_common.py", line 538, in __init__
    self.background = bg
  File "/home/samuel/.local/lib/python3.8/site-packages/urwid/display_common.py", line 678, in _set_background
    raise AttrSpecError(("Unrecognised color specification " +
urwid.display_common.AttrSpecError: Unrecognised color specification in background ('black,bold')
```

`vit --help` works fine, which suggests that the issue isn't with `vit` per se but it's when the background color needs to be set when kicking off the main vit entry point script. 

I'm on vit 2.1.0:
```
$ vit --version
2.1.0

$ which vit
/home/samuel/.local/bin/vit
```

Normally I would file a corresponding issue with the theme author, but this isn't the only theme with have gotten me issues with `vit`. If we focus on the exception,

> Unrecognised color specification in background ('black,bold')

This suggest that any themes using the color convention may break vit. Would this be something interesting to look at? Maybe a try-catch / finally block, that upon exception, ignore the color specification and still launch vit in its default color anyway?

**Comment by thehunmonkgroup** [comment]
Can you provide the exact line in that theme that throws the error?

**Comment by arcnmx** [comment]
[`include taskwarrior-base16-dark.theme`](https://github.com/vit-project/vit/files/8565343/taskwarrior-base16-dark.txt) produces:
```
Traceback (most recent call last):
  File "vit-2.2.0/bin/.vit-wrapped", line 9, in <module>
    sys.exit(main())
  File "vit-2.2.0/lib/python3.9/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "vit-2.2.0/lib/python3.9/site-packages/vit/application.py", line 77, in __init__
    self.refresh(False)
  File "vit-2.2.0/lib/python3.9/site-packages/vit/application.py", line 924, in refresh
    self.loop.screen.register_palette(self.theme)
  File "python3.9-urwid-2.1.2/lib/python3.9/site-packages/urwid/display_common.py", line 856, in register_palette
    self.register_palette_entry(*item)
  File "python3.9-urwid-2.1.2/lib/python3.9/site-packages/urwid/display_common.py", line 938, in register_palette_entry
    high_256 = AttrSpec(foreground_high, background_high, 256)
  File "python3.9-urwid-2.1.2/lib/python3.9/site-packages/urwid/display_common.py", line 537, in __init__
    self.foreground = fg
  File "python3.9-urwid-2.1.2/lib/python3.9/site-packages/urwid/display_common.py", line 637, in _set_foreground
    raise AttrSpecError(("Unrecognised color specification %s " +
urwid.display_common.AttrSpecError: Unrecognised color specification 'inverse' in foreground ('inverse')
```

Presumably the problematic line is `color.overdue=inverse`. These are documented in [man task-color](https://linux.die.net/man/5/task-color).

**Comment by thehunmonkgroup** [comment]
See https://github.com/vit-project/vit/blob/2.x/COLOR.md#caveats

I do believe a crash is the right behavior here. https://github.com/vit-project/vit/commit/5bbdd4ad344c1f64fd12bdb9090b500db8013a1d adds a more user-friendly message when an unsupported color definition is found.
