### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'None.filter='

### ISSUE THREAD

**Issue by pglaser-engineer** [vit-project/vit#328]
**Describe the bug**

When starting vit I get the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/vit", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vit/application.py", line 74, in __init__
    self.load_early_config()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vit/application.py", line 83, in load_early_config
    self.reports = self.task_config.get_reports()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vit/config_parser.py", line 367, in get_reports
    reports[report]['context'] = int(attrs['context'])
ValueError: invalid literal for int() with base 10: 'None.filter='
```

**To Reproduce**
```
% pip install vit
Collecting vit
  Using cached vit-2.2.0-py3-none-any.whl (95 kB)
Requirement already satisfied: tasklib>=2.4.3 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from vit) (2.4.3)
Requirement already satisfied: urwid>=2.1.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from vit) (2.1.2)
Requirement already satisfied: pytz in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from tasklib>=2.4.3->vit) (2021.3)
Requirement already satisfied: tzlocal in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from tasklib>=2.4.3->vit) (4.1)
Requirement already satisfied: pytz-deprecation-shim in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from tzlocal->tasklib>=2.4.3->vit) (0.1.0.post0)
Requirement already satisfied: tzdata in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytz-deprecation-shim->tzlocal->tasklib>=2.4.3->vit) (2021.5)
Installing collected packages: vit
Successfully installed vit-2.2.0

% vit
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/vit", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vit/application.py", line 74, in __init__
    self.load_early_config()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vit/application.py", line 83, in load_early_config
    self.reports = self.task_config.get_reports()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vit/config_parser.py", line 367, in get_reports
    reports[report]['context'] = int(attrs['context'])
ValueError: invalid literal for int() with base 10: 'None.filter='
```

**Expected behavior**
Should start without error

**Environment**
* macos 11.6.7
* python 3.10
* task 2.6.2
* tasklib 2.4.3
*

**Comment by thehunmonkgroup** [comment]
Likely an error in your TaskWarrior configuration, or a TaskWarrior setting VIT does not support yet.

I recommend you try with a vanilla/minimal TaskWarrior configuration -- if that works, you can start adding your custom configuration back until you find the issue.

**Comment by pglaser-engineer** [comment]
Thanks for the quick response. I will give your suggestion a try and report back.

**Comment by pglaser-engineer** [comment]
Yes, there were several issues:
* I had been using taskwarrior-tui, and so had a bunch of configuration udas that did not have a ``type`` specifier -- vit does not like that
* one of my context specifiers was missing the ``read`` segment -- here again vit does a more thorough job of configuration validation
* there was an alias that was interfering with my access to the vit binary (long story). 

Anyway, I am now able to start vit without incident. Thanks for your help!
