### ISSUE TITLE
Installing with pip fails when running with "No module named 'urwid.str_util'"

### ISSUE THREAD

**Issue by mrmowgli** [vit-project/vit#339]
**Describe the bug**
Pip installs vit successfully and installs the dependency in Centos Stream using Python 3.9 .
Running vit results in the following error:

```bash
$ vit
Traceback (most recent call last):
  File "/home/fisher/.espressif/python_env/idf5.2_py3.9_env/bin/vit", line 5, in <module>
    from vit.command_line import main
  File "/home/fisher/.espressif/python_env/idf5.2_py3.9_env/lib64/python3.9/site-packages/vit/__init__.py", line 2, in <module>
    from .application import Application
  File "/home/fisher/.espressif/python_env/idf5.2_py3.9_env/lib64/python3.9/site-packages/vit/application.py", line 20, in <module>
    from vit.formatter_base import FormatterBase
  File "/home/fisher/.espressif/python_env/idf5.2_py3.9_env/lib64/python3.9/site-packages/vit/formatter_base.py", line 8, in <module>
    from vit import util
  File "/home/fisher/.espressif/python_env/idf5.2_py3.9_env/lib64/python3.9/site-packages/vit/util.py", line 7, in <module>
    from urwid.str_util import calc_width
ModuleNotFoundError: No module named 'urwid.str_util'
```
Install seems to go correctly:

```bash
$ pip install vit
Collecting vit
  Downloading vit-2.3.0-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.6/97.6 kB 2.9 MB/s eta 0:00:00
Collecting tasklib>=2.4.3 (from vit)
  Downloading tasklib-2.5.1.tar.gz (23 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting urwid>=2.1.2 (from vit)
  Downloading urwid-2.1.2.tar.gz (634 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 634.6/634.6 kB 11.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: tasklib, urwid
  Building wheel for tasklib (pyproject.toml) ... done
  Created wheel for tasklib: filename=tasklib-2.5.1-py3-none-any.whl size=25472 sha256=589a557e8398c437cb740782f247c338ddbb5decb8431bcb992b24247b809c3d
  Stored in directory: /home/fisher/.cache/pip/wheels/96/24/3e/8af6cb4e6abcb4a45d003b975c52c0dbd843a0a6a3f6f0a07c
  Building wheel for urwid (pyproject.toml) ... done
  Created wheel for urwid: filename=urwid-2.1.2-py3-none-any.whl size=235034 sha256=bc16b58bc0271b5e6f34b870b1b01bf96beadf7809f0f621e6ac318947589b94
  Stored in directory: /home/fisher/.cache/pip/wheels/44/ec/04/2c1080c3ee4e80e76d662ac35f0594a2a86f9df12095b05cb3
Successfully built tasklib urwid
Installing collected packages: urwid, tasklib, vit
Successfully installed tasklib-2.5.1 urwid-2.1.2 vit-2.3.0
```

**To Reproduce**
On a Centos stream machine, ensure python is at 3.9. 
Run `pip install vit`
run `pip`

**Expected behavior**
the `vit` command should bring up the vit interface.

**Comment by thehunmonkgroup** [comment]
Urwid is doing some weird stuff with their module imports. I can import that module just fine:

```
[:~/git/vit] [vit] 2.x+ ± pip freeze | grep urwid
urwid==2.1.2
[:~/git/vit] [vit] 2.x+ ± python
Python 3.11.4 (main, Jun 13 2023, 13:57:01) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urwid.str_util
>>>
```

Try this patch, if it works to fix the problem, I can commit it, as I believe this adjustment will work around the previous issue for all users:

```diff
diff --git a/vit/util.py b/vit/util.py
index acc2d61..9930147 100644
--- a/vit/util.py
+++ b/vit/util.py
@@ -2,9 +2,8 @@ import os
 import sys
 import curses
 import shlex
-from functools import reduce
 
-from urwid.str_util import calc_width
+from urwid.util import calc_width
 
 curses.setupterm()
 e3_seq = curses.tigetstr('E3') or b''
```

**Comment by mrmowgli** [comment]
Yes, this totally fixed it.
