### ISSUE TITLE
Support py3.12

### ISSUE THREAD

**Issue by chenrui333** [vit-project/vit#347]
There is some issue running with py3.12 as shown below:

```
Traceback (most recent call last):
  File "./vit/bin/vit", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "./vit/lib/python3.12/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "./vit/lib/python3.12/site-packages/vit/application.py", line 77, in __init__
    self.load_early_config()
  File "./vit/lib/python3.12/site-packages/vit/application.py", line 107, in load_early_config
    self.config = ConfigParser(self.loader)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./vit/lib/python3.12/site-packages/vit/config_parser.py", line 103, in __init__
    self.config = configparser.SafeConfigParser()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

relates to https://github.com/Homebrew/homebrew-core/pull/151313

**Comment by thehunmonkgroup** [comment]
https://pypi.org/project/vit/2.3.2/

**Comment by chenrui333** [comment]
Thanks!
