### ISSUE TITLE
Issue with vit 2.3.1 and Python 3.12.3

### ISSUE THREAD

**Issue by akastos-s** [vit-project/vit#355]
**Describe the bug**
Errormessage:
```
Traceback (most recent call last):
  File "/usr/bin/vit", line 33, in <module>
    sys.exit(load_entry_point('vit==2.3.1', 'console_scripts', 'vit')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/usr/lib/python3.12/site-packages/vit/application.py", line 77, in __init__
    self.load_early_config()
  File "/usr/lib/python3.12/site-packages/vit/application.py", line 107, in load_early_config
    self.config = ConfigParser(self.loader)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vit/config_parser.py", line 103, in __init__
    self.config = configparser.SafeConfigParser()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

It seems, SafeConfigParser has to be replaced with ConfigParser (?).

**To Reproduce**
Start vit version 2.3.1 with Python version 3.12.3 and Taskwarrior version 3.0.2 (as it is the situation in Arch Linux).

**Expected behavior**
Vit starts without error.

**Test case**
If reproducing your issue requires any TaskWarrior setup, please produce a [test case](https://github.com/vit-project/vit/blob/2.x/TEST-CASE.md) script.

**Comment by thehunmonkgroup** [comment]
@akastos-s is this still an issue?
