### ISSUE TITLE
Python error when running vit

### ISSUE THREAD

**Issue by ManuGraiph** [vit-project/vit#356]
**Describe the bug**
When running vit for the first time, after creating the automatic default config file i'm getting the following wrong key error:

```
Traceback (most recent call last):
  File "/usr/bin/vit", line 33, in <module>
    sys.exit(load_entry_point('vit==2.3.2', 'console_scripts', 'vit')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/usr/lib/python3.12/site-packages/vit/application.py", line 81, in __init__
    self.refresh(False)
  File "/usr/lib/python3.12/site-packages/vit/application.py", line 963, in refresh
    self.bootstrap(load_early_config)
  File "/usr/lib/python3.12/site-packages/vit/application.py", line 158, in bootstrap
    self.markers = Markers(self.config, self.task_config)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vit/markers.py", line 42, in __init__
    self.udas = uda.get_configured(self.task_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vit/uda.py", line 10, in get_configured
    return {k:v['type'] for k, v in subtree['uda'].items()}
              ~^^^^^^^^
KeyError: 'type'
```

Since i don't know (first time using taskwarrior) what the markers or uda is, i sadly can't debug it myself.

Any idea what could it be?
Thanks in advance!

**Comment by ManuGraiph** [comment]
Nvm, some garbage got into my .taskrc that was messing the dict.
