### ISSUE TITLE
crash when giving invalid format to `wait`

### ISSUE THREAD

**Issue by fenugrec** [vit-project/vit#360]
**Describe the bug**
vit should either do some validation on the arguments to `wait` or handle errors from task backend ?

In addition, after restarting `vit` , no tasks appear anymore,  only the list with the text "Loading..."
The db is probably intact, since running 'task' directly shows the expected list.

**To Reproduce**
- select task
- press 'w'
- just type '1' then Enter

**Expected behavior**
no crash, possibly error message.

** output **

```
Traceback (most recent call last):
  File "/usr/bin/vit", line 33, in <module>
    sys.exit(load_entry_point('vit==2.3.2', 'console_scripts', 'vit')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/usr/lib/python3.12/site-packages/vit/application.py", line 83, in __init__
    self.loop.run()
  File "/usr/lib/python3.12/site-packages/urwid/event_loop/main_loop.py", line 337, in run
    self._run()
  File "/usr/lib/python3.12/site-packages/urwid/event_loop/main_loop.py", line 439, in _run
    self.event_loop.run()
  File "/usr/lib/python3.12/site-packages/urwid/event_loop/select_loop.py", line 182, in run
    self._loop()
  File "/usr/lib/python3.12/site-packages/urwid/event_loop/select_loop.py", line 229, in _loop
    record.data()
  File "/usr/lib/python3.12/site-packages/urwid/display/_posix_raw_display.py", line 273, in wrapper
    return self.parse_input(event_loop, callback, self.get_available_raw_input())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urwid/display/_raw_display_base.py", line 488, in parse_input
    callback(decoded_codes, raw_codes)
  File "/usr/lib/python3.12/site-packages/urwid/event_loop/main_loop.py", line 466, in _update
    self.process_input(keys)
  File "/usr/lib/python3.12/site-packages/urwid/event_loop/main_loop.py", line 566, in process_input
    handled_key = self._topmost_widget.keypress(self.screen_size, key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urwid/widget/popup.py", line 143, in keypress
    return self._current_widget.keypress(size, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vit/application.py", line 71, in keypress
    return super().keypress(size, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/urwid/widget/frame.py", line 513, in keypress
    return self.footer.keypress((maxcol,), key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vit/multi_widget.py", line 59, in keypress
    return self.current_widget.keypress(size, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vit/command_bar.py", line 34, in keypress
    self.quit({'key': key, 'text': text})
  File "/usr/lib/python3.12/site-packages/vit/command_bar.py", line 81, in quit
    self.event.emit('command-bar:keypress', data)  # remove focus from command bar
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vit/event.py", line 16, in emit
    listener(data)
  File "/usr/lib/python3.12/site-packages/vit/application.py", line 381, in command_bar_keypress
    self.activate_message_bar('Task %s wait updated' % self.model.task_id(metadata['uuid']))
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vit/task.py", line 64, in task_id
    task = self.tw.tasks.get(uuid=uuid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tasklib/task.py", line 552, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tasklib/task.py", line 475, in __len__
    self._result_cache = list(self.__iter__())
                              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tasklib/task.py", line 480, in __iter__
    self._result_cache = self._execute()
                         ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tasklib/task.py", line 512, in _execute
    return self.backend.filter_tasks(self.filter_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tasklib/backends.py", line 316, in filter_tasks
    for line in self.execute_command(args):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tasklib/backends.py", line 279, in execute_command
    raise TaskWarriorException(error_msg)
tasklib.backends.TaskWarriorException: TASKDATA override: /.../todos
Configuration override rc.confirmation=no
Configuration override rc.dependency.confirmation=no
Configuration override rc.recurrence.confirmation=no
Configuration override rc.json.array=off
Configuration override rc.bulk=0
Configuration override rc.data.location=/.../todos
'1' is not a valid date in the '' format.
Command used: task rc.confirmation=no rc.dependency.confirmation=no rc.recurrence.confirmation=no rc.json.array=off rc.bulk=0 rc.data.location=/.../todos f2a6ccc8-6574-43ab-bc64-dc8f04eb25bf export
```

**Comment by thehunmonkgroup** [comment]
Cannot replicate, the current code is catching the error fine:

![2024-09-14_19-52](https://github.com/user-attachments/assets/11fb1a97-ab7e-45bb-9b74-fd29ec4447e0)

It's also a bit weird the error shows backtrace to the `quit` command, so not sure how you are getting to this error.

The relevant code is here: https://github.com/vit-project/vit/blob/2.x/vit/application.py#L368-L383

Are you using the latest release?

**Comment by fenugrec** [comment]
Thanks for checking this out.

> Are you using the latest release?

task 3.1.0 and vit 2.3.2 , I might try building straight from git if useful.

To test again, I temporarily moved my db to auto-create a new one; added a bogus task, entered again `wait` then `1` , and it crashed with the same trace.  (side-note, this worries me that my "good" db cannot be loaded with vit anymore, but that's a separate topic)

Is there a way to get some kind of debug output pre-crash ?

**Comment by fenugrec** [comment]
Here is a db that vit cannot open anymore after doing "wait 1" .

[taskchampion.zip](https://github.com/user-attachments/files/17004217/taskchampion.zip)

**Comment by thehunmonkgroup** [comment]
Looks like you're using the 3.x version of Taskwarrior. I haven't done any work for that version yet.

As far as I understand, the CLI interface was the same as the 2.6.x series.

I don't have any plans to work on any 3.x compatibility yet, still waiting for that series to stabilize.

You might consider moving back to 2.6.x, or digging into the VIT code and submitting a PR.

**Comment by fenugrec** [comment]
>  the 3.x version of Taskwarrior. I haven't done any work for that version yet.

Ah, understood. Didn't notice if this was mentioned in the docs, although as you said one could've expected the CLI semantics to remain unchanged.

> digging into the VIT code

Unfortunately out of scope for me, and insufficient brain-hours : )

**Comment by fenugrec** [comment]
Actually looks like an upstream issue : https://github.com/GothenburgBitFactory/taskwarrior/issues/3444

simply running `task export` will trigger the bug.

I guess this can be closed, or kept for reference until upstream is fixed ?

**Comment by thehunmonkgroup** [comment]
No need to keep this open, glad the issue was tracked down.
